### PR TITLE
 Implementation of player sorting

### PR DESCRIPTION
**Pull request by nicolasdellatorre**
Here there is a beginning of the player sorting system by a draggable list. It doesn't work at the moment.
This is the reference web site:  https://www.geeksforgeeks.org/create-a-drag-and-drop-sortable-list-using-html-css-javascript/
I can't understand why the draggable list doesn't work.

### CODE REVIEW

**Comment by adolfintel** [comment]
The draggable list itself works visually, the problem is that you're not also moving items in the players array, so they stay in the original order.

Before you continue, I pushed some fixes to master, you should base your changes on the new version.

**Comment by nicolasdellatorre** [comment]
I know that I have to implement the system which take the player order from the interface and put it in the schedule (there is a comment at line 1143 into the javascript). I was referring to the graphic only: on my browser I can't see the draggable list working...
However, I'll fork again the repostory and try to make the draggable list work visually also on my browser.

**Comment by nicolasdellatorre** [comment]
> I know that I have to implement the system which take the player order from the interface and put it in the schedule (there is a comment at line 1143 into the javascript). I was referring to the graphic only: on my browser I can't see the draggable list working... However, I'll fork again the repostory and try to make the draggable list work visually also on my browser.

Edit: I tried on Firefox and it works as you said; but the interface doesn't work on Chrome.

**Comment by adolfintel** [comment]
I just noticed in the CSS at line 37, dragging is disabled for all elements on chromium browsers.

**Comment by nicolasdellatorre** [comment]
The "firstPlayer" feature has been completely removed. Now, in the schedule, the player are sorted by the order decided into the "playerOrder" slide by using the draggable list. The player order is decided before every turn as the new rules of the game.

**Comment by adolfintel** [comment]
Good :)
It works well, before I merge it, can you try making it so that the player list is draggable instead of having a separate slide for that? They're divs so it should be possible to add the draggable attribute.

**Comment by nicolasdellatorre** [comment]
I worked on what you said: now there is no longer a separate slide for the player sorting. The player list is draggable (there is an icon that makes the user understand that each player's box is draggable) and at the end of each round there is a simple interface to decide the player order for the next round directly in the "endRound" slide.

**Comment by nicolasdellatorre** [comment]
I worked on what you said: now there is no longer a separate slide for the player sorting. The player list is draggable (there is an icon that makes the user understand that each player's box is draggable) and at the end of each round there is a simple interface to decide the player order for the next round directly on the "endRound slide.

**Comment by adolfintel** [comment]
Bravo :blush: 

That wasn't easy to implement

**Pull request merged**
